#ifndef POKEPLATINUM_CONSTANTS_PLATINUM_VERSION_H
#define POKEPLATINUM_CONSTANTS_PLATINUM_VERSION_H

#define POKEPLATINUM_VERSION_US_REV0 0
#define POKEPLATINUM_VERSION_US_REV1 1
#define POKEPLATINUM_VERSION_EU      2

#ifndef POKEPLATINUM_VERSION
#define POKEPLATINUM_VERSION POKEPLATINUM_VERSION_US_REV1
#endif

#endif // POKEPLATINUM_CONSTANTS_PLATINUM_VERSION_H
